### ISSUE TITLE
Elegir repositorio

### ISSUE THREAD

**Issue by yjx0003** [yjx0003/GESPRO_PracticaGestionTareas_1718#1]

**Comment by mpl0045** [comment]
Herramientas consideradas:

GitHub
Bitbucket
GitLab
Herramienta elegida:

GitHub
GitHub es la plataforma web de hospedaje de repositorios por excelencia. Ofrece todas las funcionalidades de Git, revisión de código, documentación, bug tracking, gestión de tareas, wikis, red social... y numerosas integraciones con otros servicios.

Utilizaremos GitHub como plataforma principal donde hospedaremos el código del proyecto, la gestión de proyecto (gracias a ZenHub) y la documentación (gracias a sus wikis).
