### ISSUE TITLE
Elegir herramienta de gestión de proyecto

### ISSUE THREAD

**Issue by yjx0003** [yjx0003/GESPRO_PracticaGestionTareas_1718#2]

**Comment by aog0036** [comment]
**Herramientas consideradas:**

- ZenHub

- Trello

- Waffle

- VersionOne

- XP-Dev

- Herramienta

 elegida:

- ZenHub

ZenHub es una herramienta de gestión de proyectos totalmente integrada en GitHub. Proporciona un tablero canvas en donde cada tarea representada se corresponde con un issue nativo de GitHub. Cada tarea se puede priorizar dependiendo de su posición en la lista, se le puede asignar una estimación, uno o varios responsables y el sprint al que pertenece. ZenHub también permite visualizar el gráfico burndown de cada sprint. Es gratuita para proyectos pequeños (max. 5 colaboradores) o proyectos open source.
