### ISSUE TITLE
Elegir IDE

### ISSUE THREAD

**Issue by yjx0003** [yjx0003/GESPRO_PracticaGestionTareas_1718#4]

**Comment by aog0036** [comment]
**## Herramientas consideradas:**

- Android Studio
- Eclipse
**## Herramienta elegida:**

- Android Studio
Android Studio es el IDE oficial para el desarrollo de aplicaciones Android. Está basado en IntelliJ IDEA de JetBrains. Proporciona soporte para Gradle, emulador, editor de layouts, refactorizaciones específicas de Android, herramientas Lint para detectar problemas de rendimiento, uso, compatibilidad de versión, etc.

No se descarta el uso de algún otro IDE para la realización de prototipos fuera de la plataforma Android.
