### ISSUE TITLE
Elegir herramientas de documentación

### ISSUE THREAD

**Issue by yjx0003** [yjx0003/GESPRO_PracticaGestionTareas_1718#6]

**Comment by aog0036** [comment]
**Herramientas consideradas:**

- Microsoft Word
- LaTeX
- GitHub Wikis

**Herramienta elegida:**
- GitHub Wikis
GitHub ofrece junto al repositorio de código una sección para la creación de una wiki. En ella se pueden crear diferentes páginas. El texto se formatea siguiendo la sintaxis de Markdown.

La documentación se irá desarrollando en la wiki y de cara a la entrega del proyecto se exportará a LaTeX.

- LaTeX
LaTeX es un sistema de composición de textos que genera documentos con una alta calidad tipográfica. Es ampliamente utilizado para la generación de artículos y libros científicos, principalmente por su potencia a la hora de representar expresiones matemáticas.
